import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Suspense } from 'react'; // 👈 Suspense 추가
import Footer from '@/components/layout/Footer';
import SiteHeader from '@/components/layout/SiteHeader'; // 👈 새로 만든 컴포넌트 import
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Hanaro TechBlog',
  description: 'Generated by create next app',
};

// async 키워드 제거 (이제 여기서 await 안 함)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />

          <Suspense
            fallback={
              <div className="h-16 w-full border-b bg-background/80 backdrop-blur" />
            }
          >
            <SiteHeader />
          </Suspense>

          <main className="flex-1">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
